### ISSUE TITLE
Support dependencies

### ISSUE THREAD

**Issue by jabranham** [purcell/nix-emacs-ci#11]
Would be nice if there were an easy way to specify what dependencies should be installed. e.g. 
most of the `flycheck-foo` packages depend on flycheck.

Thanks for working on this, BTW. Looks pretty nice!

**Comment by purcell** [comment]
I think that's out of scope for this project, really: I just want to distribute a range of emacs binaries, not provide a full development environment. I think you're looking for `cask`? I might consider making other Github Actions that conveniently wrap things like `cask`, and that can byte-compile elisp, or run `package-lint` on a named file.
