### ISSUE TITLE
Faster installations

### ISSUE THREAD

**Issue by purcell** [purcell/nix-emacs-ci#12]
If the client machine does not have or need Nix, then using these binaries involves installing Nix and then Cachix, which has an overhead: `evm` binaries take a few seconds to install, vs. around a minute for this method.

I'm personally okay with that, because Nix then offers helpful further tooling for installing other programs, but ideally the overhead could be minimised in simple cases, not least to avoid excessive use of compute resources.

It would be possible to pre-build tarballs that contain each binary and its dependency closure. This way, if the CI machine does not already have Nix installed, it could simply download the tarball, unpack it under `/nix`, and then modify the user's PATH accordingly (e.g. with a symlink under `/usr/local/bin`).

The challenge here would be building the machinery to cache those tarballs, retrieve the correct ones, and generally manage unpacking them in the "Nix-less" scenario.

/cc @npostavs

**Comment by DamienCassou** [comment]
I have opened https://github.com/purcell/nix-emacs-ci/issues/14 to discuss faster installation on Travis.

**Comment by alphapapa** [comment]
I found this issue after posting https://github.com/purcell/setup-emacs/issues/4.  Maybe GitHub Actions caching could help in some way.

**Comment by purcell** [comment]
Closing, really not going to work on removing Nix from the equation.
