### ISSUE TITLE
hash mismatch in fixed-output derivation '*-package-keyring.gpg'

### ISSUE THREAD

**Issue by Silex** [purcell/nix-emacs-ci#131]
Hello,

Since a while manual builds seems to fail without cachix:

https://github.com/Silex/docker-emacs/actions/runs/3846888771/jobs/6552701354

The dockerfile is https://github.com/Silex/docker-emacs/blob/2133e0c2604122aeeb0b7ccf0f33547aa3ed55b9/25.3/debian/Dockerfile

By adding cachix everything builds normally.

**Comment by purcell** [comment]
Looks like that file changed a few days ago, and now it's hash is different, so Nix complains. Cachix would indeed mask this, because it's exactly there to cache artifacts like this, and the source nix code didn't change, ie. still requires the sames inputs. I can update the hash on my end.

**Comment by Silex** [comment]
Thanks! :+1:
