### ISSUE TITLE
Build of the release branch (emacs-29)

### ISSUE THREAD

**Issue by tarsius** [purcell/nix-emacs-ci#134]
@purcell Could you please add a snapshot version of the release branch (currently `emacs-29`), similar to how that is done for the `master` branch? That branch will remain useful after 29.1 is released. (At that time it will then be used to work toward 29.2, which may or may not ever be released).

This snapshot should probably be named `emacs-29`, like the branch. Eventually you would have to add `emacs-30`. When that happens, I wouldn't remove `emacs-29` right away and maybe even keep it around until the `emacs-31` branch is created (this would reduce the risk of breaking CI in repositories that are a bit slow to update).

**Comment by purcell** [comment]
Something like this would be possible, yes. I might be inclined to call it something like `emacs-29-snapshot` or something similar, just to make clear that it doesn't usually correspond to a specific official release.

I don't know if I can ever safely remove targets, due to breakage, and I'm wary of proliferation, so I might even suggest as an alternative something like `emacs-release-snapshot`, which would aim to always build the head of the highest-numbered release branch. Just like with the snapshot build, there *is* still a version number attached to it.

**Comment by tarsius** [comment]
Makes sense. `emacs-release-snapshot` would work for me.

(If you add this here, do you still need to update `setup-emacs` (documentation aside), or what that just work?)

**Comment by purcell** [comment]
It would just work, but I'd add it to the CI there anyway.

**Comment by purcell** [comment]
What's the easiest way to see what the current version numbers are for HEAD and the release branch respectively? Currently the HEAD build _here_ is marked as 29.0.50.

**Comment by purcell** [comment]
WIP in #135, just pending info about what placeholder version numbers to use.

**Comment by tarsius** [comment]
> What's the easiest way to see what the current version numbers

I don't know if its the easiest, but in the past I have used:

```shell
get_version() {
    # for >=25: AC_INIT(GNU Emacs, MM.m, ...)
    # for >=29: AC_INIT([GNU Emacs], [MM.m], ...)
    git show "$1:configure.ac" |
    sed -n 's/^AC_INIT(\[\?GNU Emacs\]\?, *\[\?\([0-9.]*\).*/\1/p' ||
    die "failed to detect version"
}
get_version HEAD
get_version emacs-29
```

**Comment by purcell** [comment]
Okay, cool, basically just needed to know in which file to look — thanks! Unsure if I can automatically determine it as part of the build.

**Comment by purcell** [comment]
The `emacs-29` branch says 30.0.50, is that expected? (At least according to [emacsmirror/emacs](https://github.com/emacsmirror/emacs/tree/emacs-29).)

**Comment by tarsius** [comment]
No, I've messed up mirroring of that branch. Thanks for making me aware of this. The current value on `emacs-29` is `29.0.60`.

**Comment by minad** [comment]
Thanks guys, I was also about to ask for this!

**Comment by purcell** [comment]
Does #135 look sane? Should be ready to merge afaict.

**Comment by purcell** [comment]
Now merged and available.

**Comment by tarsius** [comment]
> Now merged and available.

Too fast. I am not done banging on my own actions yet. :face_with_spiral_eyes:

Thanks!

**Comment by purcell** [comment]
Haha! Thanks for your help, and enjoy your weekend!
