### ISSUE TITLE
Faster installation on Travis

### ISSUE THREAD

**Issue by DamienCassou** [purcell/nix-emacs-ci#14]
What about having a Travis language "emacs-nix" which would contain nix pre-installed so installing Emacs is very fast?

**Comment by purcell** [comment]
Interesting. How does that work? Custom images? I think even the existing `nix` language installs `nix` on demand.

**Comment by DamienCassou** [comment]
Steve Purcell <notifications@github.com> writes:
> Interesting. How does that work? Custom images? I think even the
> existing `nix` language installs `nix` on demand.

I thought we could have pre-built images but it doesn't seem to be the
case. We could probably use that to cleanup the .travis.yml files but
the improvement would be small. I suggest we close this issue, sorry for
the noise.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by purcell** [comment]
Yep, thanks.
