### ISSUE TITLE
Low-level Nix usage

### ISSUE THREAD

**Issue by akirak** [purcell/nix-emacs-ci#16]
I'm trying to use your Nix derivation (not the executable) with my [emacs-package-checker](https://github.com/akirak/emacs-package-checker/tree/v1/master). It's a test runner that is 100% configured in Nix and uses a Nix package to get Emacs. The experiment was almost successful with [this Nix configuration](https://github.com/akirak/poly-vue/blob/scratch/github-action/default.nix) and [this Github workflow configuration](https://github.com/akirak/poly-vue/blob/scratch/github-action/.github/workflows/test.yml). 

There is one odd thing, though. When I use the Emacs derivation with `pkgs.emacsPackagesNgGen` (which is a recommended way to extend Emacs in NixOS), I receive an error like this:

```
error: Package ‘emacs-with-packages-25.1’ in
/nix/store/rh1mrwq3z8iym1j3n4ryav63almylndc-emacs-ci/emacs-ci/emacs.nix:67
is not supported on ‘x86_64-linux’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.
```

It claims the platform isn't supported, even though your [emacs.nix](https://github.com/purcell/nix-emacs-ci/blob/master/emacs.nix) specifies `platforms.all` as the supported platforms. It didn't happen when I used an Emacs package from the official nixpkgs.  

I was able to prevent the issue by overriding `meta.platforms` as follows:

```nix
{ pkgs ? import <nixpkgs> {},
  emacs ? (import (builtins.fetchTarball "https://github.com/purcell/nix-emacs-ci/archive/master.tar.gz")).emacs-25-2
}:
let
  emacs-workarounded = emacs // {
    meta.platforms = pkgs.stdenv.lib.platforms.all;
  };
in
# Use emacs-workarounded instead of emacs
```

I have no idea why this is necessary, but it shouldn't be here. How can I use an Emacs derivation in your `default.nix` without a workaround like this?

**Comment by purcell** [comment]
I wonder if it's because `meta.platforms` in the `emacs.nix` comes from the `stdenv`, which is often not the same `stdenv` that you would normally see in the `nixpkgs` top level.

**Comment by akirak** [comment]
It turns out that this seems to be an issue with older versions of nixpkgs. 

I inspected the value of `meta.platforms` with the following expression:

```
    builtins.trace (builtins.length emacs.meta.platforms)
      (builtins.trace (builtins.head emacs.meta.platforms) emacs);
```

In release 19.09:

> trace: 37
> trace: aarch64-linux

In release 19.03:

> trace: 1
> trace: { }

After changing `pkgs` in the `default.nix` of `nix-emacs-ci` as follows, my script successfully ran:

```
  pkgs = import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/release-19.03.tar.gz") {};
```

All you need to do seems to be upgrade nixpkgs to 19.09 (or even the unstable version). Thanks.
