### ISSUE TITLE
Issue when loading sqlite3

### ISSUE THREAD

**Issue by pkryger** [purcell/nix-emacs-ci#160]
Using this repository for a CI testing of [`exordium`](https://github.com/emacs-exordium/exordium) Emacs configuration. Nothing fancy: mostly ensure that configuration can be loaded and run some unit tests.

`forge` is one of packages `exordium` uses. IIUC, `forge` uses `emacsql` which in turn requires `sqlite3` (unless `sqlite-available-p` yields t, can be case on Emacs-29, see [this commit](https://github.com/magit/emacsql/commit/64012261f65fcdd7ea137d1973ef051af1dced42)). `sqlite3` compiles small C module [that requires `-lsqlite3`](https://github.com/pekingduck/emacs-sqlite3-api/blob/b513b71012f61895f771fc6948d6511ea8ded0a6/Makefile#L3) to be visible for linker. Without it the following diagnostic is produced when I add `(use-package sqlite3)` to `exordium`:
```
Error (use-package): sqlite3/:catch: Module could not be opened: "/home/runner/.emacs.d/elpa-28.2/sqlite3-20230315.1221/sqlite3-api.so", "libsqlite3.so.0: cannot open shared object file: No such file or directory"
```

When the startup is performed under `(setq debug-on-error t)` (which greatly helps debugging issues) the CI run fails because of the diagnostics above. 

I'm not sure if this is the right place to address the issue (i.e., would adding `sqlite3` library to nixOS, something similar was done [here](https://github.com/NixOS/nixpkgs/commit/5bf1f8fd50d57e285c6b495e9c63ff03d5f52a6f)) but maybe some answers will help me to understand the issue better.

**Comment by purcell** [comment]
Since `exordium` uses `use-package`, you might consider using the `emacsWithPackagesFromUsePackage` functionality from https://github.com/nix-community/emacs-overlay. I _think_ that you should be able to combine that with the overlay provided in this repo to compose Emacs variants with the `use-package`-declared packages pre-installed, and that should take care of any binary dependencies.

**Comment by purcell** [comment]
(And @damiencassou might be interested in commenting here.)

**Comment by DamienCassou** [comment]
Did you find a workaround @pkryger? You might be interested into using `withPackages` as described in https://nixos.org/manual/nixpkgs/stable/#sec-emacs-config. I'm not sure how to tweak nix-emacs-ci so it uses `withPackages`.

**Comment by piotrkwiecinski** [comment]
I believe this is doable now after this was merged https://github.com/purcell/nix-emacs-ci/pull/170 . 
Could be done the same way as @akirak added tree-sitter grammar here https://github.com/emacs-php/php-ts-mode/pull/20/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0

**Comment by akirak** [comment]
@pkryger As commented in https://github.com/purcell/nix-emacs-ci/issues/160#issuecomment-1521908530, you should be able to build and test the config using `emacsWithPackagesFromUsePackage` and a stable Emacs executable in Nix. It should be possible to swap the normal Emacs executable with `nix-emacs-ci`. If the former succeeds but latter does not, it will be an issue with `nix-emacs-ci`.

**Comment by purcell** [comment]
FWIW, the builds of Emacs >= 29 here now have the built-in sqlite support embedded.
