### ISSUE TITLE
emacs 27 versions?

### ISSUE THREAD

**Issue by ibizaman** [purcell/nix-emacs-ci#22]
Hi,

Are there any plans to merge the [try-27-pre](https://github.com/purcell/nix-emacs-ci/compare/try-27-pre) branch into master?

**Comment by purcell** [comment]
I thought about this, but I plan to wait for the official release. I don't want to get into maintaining `pre` versions. Also they'd have to be labelled as `27` and not `27-pre`, since if people started using the latter, I'd either have to keep that working forever or break builds by removing it.

**Comment by ibizaman** [comment]
Makes senses, thanks for answering!

**Comment by purcell** [comment]
You can bet I'll have support added here promptly after the release: the `try-27-pre` branch was to make sure that will be possible without unexpected complications. :-)  Happy emacsing!
