### ISSUE TITLE
Emacs 25.2 fails

### ISSUE THREAD

**Issue by Silex** [purcell/nix-emacs-ci#261]
Hello,

https://github.com/Silex/docker-emacs/actions/runs/8442629426/job/23124462606

Not sure why this happens, 25.1 and 25.3 build just fine. Only 25.2 fails.

**Comment by Silex** [comment]
The first time it happened is two weeks ago: https://github.com/Silex/docker-emacs/actions/runs/8241693263

But I don't see any relevant commits for the 12th march that could explain it.

Probably some subtle bugs after a nix update?

**Comment by purcell** [comment]
Hmm, not sure, sorry. That version is working okay for me, e.g. here in this repo, but also in the `package-lint` CI. Could be nix version related, a cachix issue, flake vs. non-flake install (I use the former).

**Comment by Silex** [comment]
Hello,

I confirm it works with flake and fails with the non-flake install:

``` Dockerfile
FROM nixos/nix
RUN nix-env -iA cachix -f https://cachix.org/api/v1/install
RUN cachix use emacs-ci
RUN nix-env -iA emacs-25-2 -f https://github.com/purcell/nix-emacs-ci/archive/master.tar.gz
```

But I also see in the github action that there is a flake install that looks simpler:

``` bash
nix --accept-flake-config "github:purcell/nix-emacs-ci#emacs-25-2"
```

I'll switch my scripts to the flake install.

**Comment by Silex** [comment]
Fixed on my side in https://github.com/Silex/docker-emacs/commit/ad392b73689969d1d0c18b78775161386b43064b

You can close this issue if you are ok with 25.2 failing in non-flake installs.

**Comment by purcell** [comment]
Cool. And yeah, I'll close it for now because I haven't heard other reports, and it would take a bit of effort to reproduce it here — in the meantime the flake method is better supported. Thanks for the update!

**Comment by Silex** [comment]
If you want to reproduce, just copy the contents above in a Dockerfile and `docker build -t test .` inside the same folder.
