### ISSUE TITLE
Emacs 26/27 support

### ISSUE THREAD

**Issue by vemv** [purcell/nix-emacs-ci#267]
Hi!

Was 26/27 support dropped?

In principle we still intend to support it in CIDER but recently encountered the following in GHA:

> error: flake 'github:purcell/nix-emacs-ci' does not provide attribute 'packages.aarch64-darwin.emacs-27-2', 'legacyPackages.aarch64-darwin.emacs-27-2' or 'emacs-27-2'
         Did you mean one of emacs-28-2, emacs-29-2, emacs-28-1, emacs-29-1 or emacs-29-3?

Thoughts?

Thanks - V

**Comment by purcell** [comment]
> Was 26/27 support dropped?

Nope, not at all. This set of images has never included Apple Silicon builds of Emacs older than 28.1, because those versions simply do not build on this architecture.

**Comment by purcell** [comment]
Yes, I'd guess so. But if they have Rosetta installed, you can use `--system x86_64-darwin` to use the x86 builds from here.

**Comment by vemv** [comment]
Thanks much for all the info!

**Comment by purcell** [comment]
It looks like until Jun 2024 you can run Darwin builds on `macos-11` if you need to test older Emacsen. This will affect lots of elisp projects, and I imagine the best choice for most will be to test a wider version range of Emacs version on Linux, and only a few on `macos-latest`.

**Comment by purcell** [comment]
What you perhaps didn't notice was that your Emacs 28 builds would have needed to build Emacs from source each time, because I wasn't previously able to populate the build cache on that platform. So #268 is me addressing that.
