### ISSUE TITLE
GCC 4.9 has been removed from nixpkgs

### ISSUE THREAD

**Issue by akirak** [purcell/nix-emacs-ci#311]
`gcc49Stdenv` has been removed from nixpkgs (https://github.com/NixOS/nixpkgs/pull/341254), so we can no longer continue to support Emacs versions older than 25 for Linux.

From [a recent build log](https://github.com/purcell/nix-emacs-ci/actions/runs/11122467852/job/30903837618?pr=310), we got the following error message:

> … while calling the 'throw' builtin
at /nix/store/y12nnpkkps5qlq3hn2jrm494j7227ik9-source/pkgs/top-level/aliases.nix:527:17:
526|   gcc49 = throw "gcc49 has been removed from Nixpkgs, as it is unmaintained and obsolete"; # Added 2024-09-11
527|   gcc49Stdenv = throw "gcc49Stdenv has been removed from Nixpkgs, as it is unmaintained and obsolete"; # Added 2024-09-11
528|   gcc6 = throw "gcc6 has been removed from Nixpkgs, as it is unmaintained and obsolete"; # Added 2024-09-13
  error: gcc49Stdenv has been removed from Nixpkgs, as it is unmaintained and obsolete

It's time for us to drop support for those versions?

**Comment by akirak** [comment]
#312 is a PR to drop the unsupported Emacs versions, but it has got another build error on Darwin. Please wait until the issue is fixed.

**Comment by purcell** [comment]
I think first I'd like to see whether we can build with a gcc7 and maintain support for 24.x. It took a while to figure this out the first time — it's possible that a small patch or GCC compiler args might allow things to work. We can also consider pinning an older nixpkgs in the flake just for those very old versions. Even when I started this project Emacs 24 was very old, but yes, there's could be a point where a) almost nobody cares, and b) it's too much effort to keep very old versions compilable.

**Comment by akirak** [comment]
> it's possible that a small patch or GCC compiler args might allow things to work.

Following this advice, I have opened a new PR #315. It turns out that no change was needed to build the oldest versions with the default `stdenv` now. Thank you @purcell for the advice!
