### ISSUE TITLE
Need tests to ensure MELPA is usable over HTTPS with Emacs 24.x

### ISSUE THREAD

**Issue by purcell** [purcell/nix-emacs-ci#32]

**Comment by purcell** [comment]
Thoughts on this, @akirak? I'm thinking I should just run the tests outside of Nix. I can't see that the CI was doing that before your PR - am I wrong?

Basically the issue here was that when the SSL config changed on melpa.org recently, the Emacs 24.x builds here stopped being able to access MELPA, and I didn't notice a failure, so I'd like to make sure I see it in future.

**Comment by akirak** [comment]
@purcell Yes, you are right. You can run Emacs without wrapping it with `emacsWithPackages`:

```sh
nix-shell -p '(import ./default.nix).emacs-27-1' --run "emacs --no-init-file --batch tests.el"
```

The test here should be to load `package.el`, refresh the package databases, and install some packages from MELPA.

`tests/default.nix` also looks like having room for improvement. I will think about it later.
