### ISSUE TITLE
Where to start? (Minimal example?)

### ISSUE THREAD

**Issue by TinaRussell** [purcell/nix-emacs-ci#35]
I want to add continuous integration to my Emacs project at https://github.com/TinaRussell/hermeneus but I don’t know anything about `.travis.yml`, Nix, makefiles, etc. How would I get started? (I know https://github.com/rolandwalker/emacs-travis provides a minimal example for using Travis CI with an Emacs package but of course it’s out of date, hence this project.) Or, to put it another way, are there plans for the documentation to include an explanation and/or a minimal example of how to use this project, for those of us new to all this? Thank you!

**Comment by purcell** [comment]
Hi Tina - does it have to be Travis? Otherwise, I'd consider using Github Actions for your project. I've made a "setup emacs" Action which uses `nix-emacs-ci`, and it's very easy to use, plus the repo links to examples. https://github.com/purcell/setup-emacs

I'm trying to think of some good Travis examples I could link to, but I'm coming up short: I think all my Travis projects have been moved to Actions at this point, and Travis is generally falling out of favour in the community.

**Comment by TinaRussell** [comment]
Oh, okay. No, it doesn’t really have to be Travis, I simply had the impression that’s what everybody used :sweat_smile: I’ll take a look at that repo.

**Comment by TinaRussell** [comment]
Looked at the repo and some of the examples, and I still can’t quite make heads or tails of it :disappointed_relieved: So, if I use the Github Action on my repository, then it’ll suddenly contain a bunch of minimal Emacs executables for testing, plus instructions for Github to use those executables when testing, is that correct? (Or does the testing take place on my computer, with Git itself calling the shots?) And then I suppose I have to write a bunch of tests in some sort of Emacs testing framework (recommendations welcome!), and… tell Github to run those tests when committing… somehow…? …I’m in over my head again :sweat_smile:

**Comment by akirak** [comment]
@TinaRussell Hello, I'll provide you with some information on developing Emacs packages.

There are several options for testing Emacs Lisp source code, but most people seem to use either the built-in ERT or [buttercup](https://github.com/jorgenschaefer/emacs-buttercup). [Cask](https://github.com/cask/cask) can help you set up an ERT test suite.

For CI, I'd recommend [makem](https://github.com/alphapapa/makem.sh) ([an example](https://github.com/alphapapa/org-ql/)) now. [Melpazoid](https://github.com/riscy/melpazoid) is another option. Alternatively, you can write bash/Makefile for running tests, as in Purcell's [package-lint](https://github.com/purcell/package-lint) package.

On GitHub Actions, you can use a matrix to run tests on multiple versions of Emacs.

For a comprehensive list of options, you could consult [emacs-package-dev-handbook](https://github.com/alphapapa/emacs-package-dev-handbook).

You can see numerous examples on [MELPA](https://github.com/melpa/melpa/pulls)!

Good luck!
