### ISSUE TITLE
Updating emacs-snapshot

### ISSUE THREAD

**Issue by CyberShadow** [purcell/nix-emacs-ci#36]
Hi,

First of all, thank you for creating this project, and the setup-emacs GH action.

Emacs-D-Mode's test suite needs the Emacs commit c9160bda7889d9e37a9b82ef64bf711ba7e32e41. The current version of the Emacs snapshot installed by this package precedes that commit, so I attempted to make a pull request updating that version. However, I failed to do so.

I am completely unfamiliar with Nix, and even installing it was non-trivial. It is not packaged by my distribution (Arch Linux), so I needed to build a third-party package (from AUR).

Once installed, I attempted to follow the instructions in the "Low-level Nix usage, e.g. for local testing" section. README. However, the first command that it instructs to run fails:

```
$ nix-env -iA cachix -f https://cachix.org/api/v1/install
# error: creating directory '/nix': Permission denied
```

The software seems to require root privileges. So, it appears that to go forward, I must grant software that I am unfamiliar with complete privileges to my machine, and let it perform arbitrary changes to it. This seems a little unexpected considering the triviality of the task at hand, which is calculating a hash.

However, even (heart in teeth) when running the command via sudo, it still fails:

```
$ sudo nix-env -iA cachix -f https://cachix.org/api/v1/install
warning: the group 'nixbld' specified in 'build-users-group' does not exist
installing 'cachix-0.6.0'
error: the group 'nixbld' specified in 'build-users-group' does not exist
```

Searching online for that error message, I only find [an open GitHub issue from 2017](https://github.com/NixOS/nix/issues/1559), with project-specific technical discussion, but no obvious resolution for my situation. I tried a few things, such as `newgrp`, or starting the daemon and running with `NIX_REMOTE=daemon`, but none of these worked. So, I'm stuck.

As such, this issue is a request for two things:

1. Could you please update the Emacs snapshot version, e.g. to commit c63d2ef59c511c1c48c69a202907b7edfcbb19b3 (the current master)? This will allow unbreaking the Emacs-D-Mode CI.

2. Would it be possible to reduce the amount of work required to update the Emacs-snapshot version?

   Some ideas for how this could be done:
   - Provide a Dockerfile which contains all the necessary dependencies and build steps.
   - Calculate the hash as part of CI for this project. Then, the workflow would be to submit a WIP pull request with just the commit, let the CI run and fail (but print the expected hash), then add the expected hash to the PR.
   - If possible, don't require a hash at all, and make the Emacs git commit SHA-1 fully identify and validate the Emacs snapshot version.

Thanks!

**Comment by purcell** [comment]
Hi! Thanks for filing this. I can't offer to debug what's wrong with your Nix installation, sorry, but pull request #37 will update the snapshot version soon.

As for reducing the work available, it's trivial when nix is working fine, so I'm not very likely to pursue the suggested options. One thing I *have* looked at is using Niv, which would allow an update to be performed with "niv update emacs-snapshot". There are some issues with that approach currently due to Niv not handling `mirror://` URLs well, so I'm waiting on an upstream fix. This all still assumes a working Nix, though.

With that latter issue fixed, it would be feasible to have a scheduled GitHub Action which would periodically try to update the snapshot, and make it the current one if the build succeeds.

**Comment by CyberShadow** [comment]
> pull request #37 will update the snapshot version soon

Thank you!

> I can't offer to debug what's wrong with your Nix installation

My personal take-away is that Nix (as an application that runs outside of its "home" NixOS environment) is not yet sufficiently mature to expect anyone to be able to just install and use it.

> it's trivial when nix is working fine

Well, of course the remaining 10% of the work is easy, if you just do the other 90% of the work first ;)

There is also a matter of trust, and having to weigh the impact of installing a root-requiring program as a prerequisite for this simple task. And, what about users of operating systems which Nix doesn't support?

In any case, I discovered that there is indeed an easier way to calculate the hash:

```console
$ nix-hash --type sha256 --flat --base32 0d0aad213f941efc0fa0ec032e37dc9c2b08c9fb.tar.gz
041q0k58qfw2fjz6j9zf152jhkzn8zc8xg35aprxhndinf1cakml
```

Nix uses a weird custom "base32" variant which is unlike every other standard. The best I could do to calculate that hash using only standard tools was:

```bash
printf %65s "$( ( printf "obase=16; ibase=16; " ; sha256sum 0d0aad213f941efc0fa0ec032e37dc9c2b08c9fb.tar.gz | cut -c 1-64 | tr a-f A-F | fold -w 2| tac | tr -d \\n ; echo ) | bc )" | tr ' ' 0 | xxd -r -p | base32 | tr ABCDEFGHIJKLMNOPQRSTUVWXYZ234567 0123456789abcdfghijklmnpqrsvwxyz
```
However, that gets the last digit wrong due to the padding.

Perhaps the `nix-hash` method could be added to the documentation.

**Comment by purcell** [comment]
There's also "nix-prefetch-url" for getting the hash. (`niv` will handle that side of things anyway once I can use it.)

> what about users of operating systems which Nix doesn't support?

That's just Windows, and I've never used Windows runners on any CI system.

I don't really want to argue the pros/cons of using Nix here, since it's exactly what is allowing me to conveniently patch, build and distribute a large number of Emacs versions on Linux and MacOS. I definitely agree that many end users will be uninterested in using Nix, and even sometimes have a hard time doing so, but this repo is just for conveniently setting up CI systems, and for that use case it works extremely well.

**Comment by purcell** [comment]
Fixed now by #37

**Comment by CyberShadow** [comment]
Thanks!

> That's just Windows, and I've never used Windows runners on any CI system.

Sorry for the confusion. I meant the *user's* operating system. They need to be able to install and run Nix to calculate the hash, which they need to do to be able to submit a pull request which updates the snapshot Emacs version, as currently suggested in the documentation.

**Comment by akirak** [comment]
@CyberShadow Hello, I was once a user of Arch Linux and now using NixOS. I don't know why you even need an AUR package for installing Nix. I'd recommend following the official instruction: https://nixos.org/manual/nix/stable/#sect-single-user-installation 

I no longer use Arch, but I have been using Nix for a couple of years on Debian-based systems as well. You usually don't have to run Nix commands with `sudo`. Alternatively, you could use a Docker/OCI image containing `nix` executable for your build task.

> And, what about users of operating systems which Nix doesn't support?

Nix supports Linux and Mac, which is way better than supporting only one of them. And Purcell has worked around for building Emacs on both platforms. For native Windows, there is an alternative: https://github.com/jcs090218/setup-emacs-windows

**Comment by CyberShadow** [comment]
> @CyberShadow Hello, I was once a user of Arch Linux and now using NixOS.

Cool :) I looked into NixOS a while ago, and decided that I would be happier with writing a configuration manager (with some functional aspects) for Arch Linux instead. https://github.com/CyberShadow/aconfmgr#aconfmgr-vs-nixos

> I don't know why you even need an AUR package for installing Nix.

I followed the instructions in the Arch Linux documentation (the wiki):
https://wiki.archlinux.org/index.php/Nix#Installation

It's possible that there is a problem specifically with that package.

**Comment by akirak** [comment]
> I would be happier with writing a configuration manager (with some functional aspects) for Arch Linux instead.

That's great, but I am unwilling to discuss this topic.

**Comment by purcell** [comment]
> Sorry for the confusion. I meant the _user's_ operating system. They need to be able to install and run Nix to calculate the hash, which they need to do to be able to submit a pull request which updates the snapshot Emacs version, as currently suggested in the documentation.

Yes, true. Well, the *best* outcome will be if I can automate the whole process! :-)

**Comment by purcell** [comment]
> That's great, but I am unwilling to discuss this topic.

This could come across as impolite, but there was probably a misunderstanding due to all our different native languages.

**Comment by akirak** [comment]
> This could come across as impolite, but there was probably a misunderstanding due to all our different native languages.

Thanks for the lesson!

**Comment by CyberShadow** [comment]
[It's green now! Thanks again!](https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/runs/2053922376?check_suite_focus=true)

> That's great, but I am unwilling to discuss this topic.

No problem. I apologize for the misunderstanding.

> I can't offer to debug what's wrong with your Nix installation

Now that I've become more familiar with what Nix does and how it works, upon re-reading the Arch Linux documentation, I believe I understand the cause of the problem: the `nix` package, which contains only the software, is insufficient to allow `nix` to work and build packages. I also needed to install `archlinux-nix`, which includes the necessary system changes, such as user groups, and a bootstrapping script. (Though, this is not required to run `nix-hash`.)

**Comment by purcell** [comment]
Ah great! Yes, that would explain why it wasn't working. Glad you figured it out.
