### ISSUE TITLE
ARM 32/64 packages

### ISSUE THREAD

**Issue by Silex** [purcell/nix-emacs-ci#41]
Hello!

I've decided to give the "nix-in-docker" route a go.

If I understood correctly right now `nix-emacs-ci` does not work on arm32v7/arm64v8.

Are you interested in supporting these archs? I can provide a arm server to help (the one I use to build my arm images).

Adding @NicolasPetton & @DamienCassou to the loop as they are probably interested.

**Comment by purcell** [comment]
Yes, I'm potentially interested. It's not of great value to me personally, nor would I expect ARM support is currently terribly useful for CI purposes, but I'd be happy to try it out. From a nix perspective, what would be necessary would be:

- nix with nix-daemon installed and running on the remote servers
- ssh access to the server as a user listed in the nix configuration's `trusted-users` list

Then arm builds can be performed remotely from a non-arm machine, so could presumably be integrated with github actions. I'm a little wary of the cost/benefit of getting it set up, if we encounter any friction along the way, as my time budget is very tight these days.

Alternatively, if there's a way to make the build server a github actions runner, that might make things even simpler.

**Comment by Silex** [comment]
> Yes, I'm potentially interested. It's not of great value to me personally, nor would I expect ARM support is currently terribly useful for CI purposes, but I'd be happy to try it out.

Hum, you made me think a little bit. AFAIK @NicolasPetton is the only one who explicitely requested ARM support. At the time I found it fun to experiment, but if *nobody* uses it I could also drop the arm support and only build amd64 images.

> From a nix perspective, what would be necessary would be:
> 
> * nix with nix-daemon installed and running on the remote servers
> * ssh access to the server as a user listed in the nix configuration's `trusted-users` list
> 
> Then arm builds can be performed remotely from a non-arm machine, so could presumably be integrated with github actions.

That looks easy to do.

> I'm a little wary of the cost/benefit of getting it set up, if we encounter any friction along the way, as my time budget is very tight these days.

I completely understand, I am in the same boat :wink:

> Alternatively, if there's a way to make the build server a github actions runner, that might make things even simpler.

Can you elaborate a little bit on that? The server is theorically free to do whatever we want...

**Comment by DamienCassou** [comment]
Philippe Vaucher ***@***.***> writes:
>> Yes, I'm potentially interested. It's not of great value to me
>> personally, nor would I expect ARM support is currently terribly
>> useful for CI purposes, but I'd be happy to try it out.
>
> Hum, you made me think a little bit. AFAIK @NicolasPetton is the only
> one who explicitely requested ARM support. At the time I found it fun
> to experiment, but if *nobody* uses it I could also drop the arm
> support and only build amd64 images.

ARM support is important for https://gitea.petton.fr/ which is hosted on
an ARM platform with ARM CI runners.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by Silex** [comment]
@DamienCassou: thanks for the feedback :+1:

**Comment by purcell** [comment]
> > Alternatively, if there's a way to make the build server a github actions runner, that might make things even simpler.
> 
> Can you elaborate a little bit on that? The server is theorically free to do whatever we want...

I *think* - but am not completely sure - that GitHub will not run actions on their own ARM machines, *but* you can self-host runners on such machines and they are supported:

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#supported-architectures-and-operating-systems-for-self-hosted-runners

If that's the case, configuring your ARM machine(s) as runners and giving me access would allow me to build on them trivially using the existing infrastructure.

**Comment by Silex** [comment]
> If that's the case, configuring your ARM machine(s) as runners and giving me access would allow me to build on them trivially using the existing infrastructure.

So if I understand correctly, right now you use github actions to build the amd64 packages and if you could use the same infrastructure you could try to build the arm32/64 packages the same way resulting in minimum efforts on your part.

The alternative would be to build something ourselves on my server that essentially does what github action do but for arm.

Let's try the self-hosted runners approach, I'll send you an email with access to the server so you can give it a try on the repository.

**Comment by purcell** [comment]
> So if I understand correctly, right now you use github actions to build the amd64 packages and if you could use the same infrastructure you could try to build the arm32/64 packages the same way resulting in minimum efforts on your part.

Yes, exactly.

> Let's try the self-hosted runners approach, I'll send you an email with access to the server so you can give it a try on the repository.

Sounds good.

**Comment by Silex** [comment]
@DamienCassou, @NicolasPetton: can you give `silex/emacs:25.1` a try (or its `-ci` `-dev` variants etc)? it's entirely built using purcell's package and is multiarch (I am mostly curious about if arm32 works, it looks like it does in my tests).

**Comment by DamienCassou** [comment]
@Silex: Nicolas' infrastructure is 64bits apparently.

**Comment by Silex** [comment]
@DamienCassou: I wonder why he explicitely asked form arm32v7 support back in the days... oh well, I'll just move forward and we'll see if he complains, he's probably the only one :-)

**Comment by DamienCassou** [comment]
@Silex: I discussed with @NicolasPetton and he told me that, even though the CPU architecture is 64bits, the OS he installed on it is 32bits. So I tried silex/emacs:25.1 but [unfortunately got a problem](https://drone.petton.fr/DamienCassou/json-process-client/4/1/2):

![2021-06-03-204751](https://user-images.githubusercontent.com/217543/120696735-2be8de80-c4ad-11eb-864d-39203d17024f.png)

This was [working fine with 27.2](https://drone.petton.fr/DamienCassou/json-process-client/3/1/2).

**Comment by Silex** [comment]
@DamienCassou: Thanks a lot. That means I'll need to build the 32 bit images manually.

Tho the more I think about it the more it is a bit silly to still support 32 bit images no? What is your take on this?

It looks like he could simply reinstall the OS to be 64 bit.

**Comment by Silex** [comment]
Ok I'm rebuilding 25.1 this time without cache so it'd be 32 bits, I'll ping you for another test :wink:

**Comment by Silex** [comment]
Working around issues with `nix` (https://github.com/NixOS/nix/issues/4894) and I found out nix on arm32 is not really supported (no binary distribution):

``` bash
case "$(uname -s).$(uname -m)" in
    Linux.x86_64) system=x86_64-linux; hash=fa6188554fb90e43f8cdf5103cf62cd9b5da785abed8512a033ab9fdf3d4188a;;
    Linux.i?86) system=i686-linux; hash=1d42f93c5c1876ca4e0341ac853b7acc2639183f9741e2627ecea2ee239622ec;;
    Linux.aarch64) system=aarch64-linux; hash=b75e33daab662013f01493234b834ba018ecf074b27dc660fab8c5318bcc45d9;;
    Darwin.x86_64) system=x86_64-darwin; hash=cab4b9c9a81ba8e734c11f2f8db19ae1677bb9c9370b735cdb00c0cfc618aa68;;
    # eventually maybe: system=arm64-darwin; hash=@binaryTarball_arm64-darwin@;;
    Darwin.arm64) system=x86_64-darwin; hash=cab4b9c9a81ba8e734c11f2f8db19ae1677bb9c9370b735cdb00c0cfc618aa68;;
    *) oops "sorry, there is no binary distribution of Nix for your platform";;
esac
```

I *guess* because my box runs both arm 32 & 64 it could theorically use the arm64 nix and build the 32 bit emacs, but that looks somewhat sketchy.

Or maybe try the manual installation of nix.

**Comment by Silex** [comment]
```
#61 [linux/arm/v7 stage-0  9/11] RUN nix-env -iA emacs-25-1 -f https://githu...
#61 41.71 copying path '/nix/store/b2kq89rmpckq0xbadh1kl697l6nmzqhl-binutils-wrapper-2.35.1' from 'https://cache.nixos.org'...
#61 41.73 copying path '/nix/store/1lb5msk1g4zx8p4w3yj8hp8sn06xw5y2-libssh2-1.9.0' from 'https://cache.nixos.org'...
#61 41.87 copying path '/nix/store/qb1ky0appvcrc8yhs1h4l63m1cwn5gs7-gcc-wrapper-9.3.0' from 'https://cache.nixos.org'...
#61 41.92 copying path '/nix/store/8wb293ciiwkgi64df5ivy6swl2q85q22-curl-7.74.0' from 'https://cache.nixos.org'...
#61 41.97 copying path '/nix/store/mqbb78lzsv4ji0j29q7mkqanfxzb6skf-libssh2-1.9.0-dev' from 'https://cache.nixos.org'...
#61 41.98 copying path '/nix/store/gwsgx5nqgjw1yada2k0kbjiczxppkhfm-curl-7.74.0-bin' from 'https://cache.nixos.org'...
#61 42.01 copying path '/nix/store/qapmba1v1lbmwffbiidpfvzwp4ngd3lh-libtool-2.4.6' from 'https://cache.nixos.org'...
#61 42.11 copying path '/nix/store/vkqvcfhagyrsagml27mkn6i7sx2i7a48-libxml2-2.9.10' from 'https://cache.nixos.org'...
#61 42.22 copying path '/nix/store/p0c8rrmmkcg7gnkvn50vsyw1awrays6k-hook' from 'https://cache.nixos.org'...
#61 42.24 copying path '/nix/store/nq9cnixm0bvw2kgdkyyjwyl1if5q8ppj-libxml2-2.9.10-bin' from 'https://cache.nixos.org'...
#61 42.26 copying path '/nix/store/kg6ngpkgfbv4nxlrqmk9fs92s1jmmrkh-ncurses-6.2-dev' from 'https://cache.nixos.org'...
#61 42.29 copying path '/nix/store/cy1w809cgzh15hhyg5lrpzqk8gsicdqn-nghttp2-1.41.0-bin' from 'https://cache.nixos.org'...
#61 42.40 copying path '/nix/store/rjncgvl851vs03k53b96sw64bqpkkkrb-stdenv-linux' from 'https://cache.nixos.org'...
#61 42.44 copying path '/nix/store/9q33m5mmv0xg68zirp2avy3n1x4pcf6r-nghttp2-1.41.0-dev' from 'https://cache.nixos.org'...
#61 42.53 copying path '/nix/store/5y37gvc2gjqbsxfwpmm87pacxpld3l8q-zlib-1.2.11-dev' from 'https://cache.nixos.org'...
#61 42.55 copying path '/nix/store/iad6y9br8pizhs43nm23ggka6f5qjn7j-curl-7.74.0-dev' from 'https://cache.nixos.org'...
#61 42.59 copying path '/nix/store/hidzx0zxjbhdz8zh7hkkf4hzcpzp88a9-libxml2-2.9.10-dev' from 'https://cache.nixos.org'...
#61 42.66 building '/nix/store/0vmypsv86lkmayxjpd6kwc9r76l4gkbx-emacs-25.1.tar.gz.drv'...
#61 42.67 builder for '/nix/store/0vmypsv86lkmayxjpd6kwc9r76l4gkbx-emacs-25.1.tar.gz.drv' failed due to signal 31 (Bad system call)
#61 42.68 cannot build derivation '/nix/store/6y5my3kv2lz4a5kzyc3lvykamyab0s1j-emacs-25.1.drv': 1 dependencies couldn't be built
#61 42.98 error: build of '/nix/store/6y5my3kv2lz4a5kzyc3lvykamyab0s1j-emacs-25.1.drv' failed
#61 ERROR: executor failed running [/bin/sh -c nix-env -iA emacs-25-1 -f https://github.com/Silex/nix-emacs-ci/archive/master.tar.gz]: exit code: 1
```

Oh well, arm32 support is really a PITA.

This box I have can run both arm32 and arm64 binaries, but inside docker apparently it tries to use arm64 all the time.

@DamienCassou: how should I contact @NicolasPetton to discuss this?

**Comment by DamienCassou** [comment]
I pinged him. Here is his website: https://nicolas.petton.fr/.

**Comment by NicolasPetton** [comment]
@Silex the CI runner is currently running on a armv7 kernel (which is arm32), because AFAIR it was the only officially supported architecture for the RaspberryPi 3 OS at the time. 

I could reinstall that box with an arm64 kernel. @DamienCassou if I do that, could you trigger a new build?

**Comment by Silex** [comment]
@NicolasPetton: supporting only amd64/arm64 would be much simpler indeed :-) I hope you are the only user of these archs.

**Comment by DamienCassou** [comment]
> if I do that, could you trigger a new build?

sure

**Comment by Silex** [comment]
@NicolasPetton: if you are ok I'll move forward and drop 32 bit, if you want me to wait for you to be ready please make some noise :wink:

**Comment by Silex** [comment]
Alright images are live! @purcell I'm not sure what cleaning up there is to do for this repository about arm64 support, anyway I'll ping about the other issues (X support etc).

**Comment by purcell** [comment]
Thanks, I've cleaned things up.
