### ISSUE TITLE
Final installation method

### ISSUE THREAD

**Issue by purcell** [purcell/nix-emacs-ci#6]
There's some early code here for using these versions in Travis, but I may improve this or even break it over time. Early adopters should watch this issue to receive notifications about changes to the recommended usage method.

**Comment by purcell** [comment]
I'll probably provide a script called something like `nix-emacs-ci` that will provide sub-commands similar to `evm`, e.g. `nix-emacs-ci use 24.4`. These would hide any nix commands, and maybe also reassuringly print the location of the `emacs` on the path: currently if one says `nix-env -iA $FOO -f ...`, this silently does nothing, so it's a bit unsafe to rely on interpolating an env var in the build matrix into this command, in case the var is misspelt.

**Comment by purcell** [comment]
For now, setting `$EMACS_CI` will cause the `travis-install` script to automatically install that version. This should actually cover most use cases quite fully.

**Comment by purcell** [comment]
Some usage in the wild: https://github.com/search?l=&q=nix-emacs-ci+++filename%3A.travis.yml&type=Code

**Comment by alphapapa** [comment]
@purcell FYI I'm using this and your `setup-emacs` action with `makem.sh` to set up CI for some of my packages.  It works really well!  Thanks for putting these together!

https://github.com/alphapapa/makem.sh#github-action

**Comment by purcell** [comment]
@alphapapa Thanks for the pointer, that looks handy.

**Comment by purcell** [comment]
Looks like the installation method isn't likely to change now, so closing this.
