### ISSUE TITLE
Any plans on emacs 28.0?

### ISSUE THREAD

**Issue by runchard** [purcell/nix-emacs-ci#63]
Currently, the version `snapshot` is point to `29.0.50`.
However, the most version close to snapshot is `27.2`.
Do we have a plan on emacs 28? or should we integrate `28.0` at this time for better integration?

**Comment by purcell** [comment]
My plan would be to add Emacs 28 once it is released. As far as I am aware, that hasn't happened yet. Generally my policy is to provide stable releases plus a dev snapshot. I don't want to mess about too much trying to track pre-releases.

**Comment by purcell** [comment]
Fixed by #65
