### ISSUE TITLE
Request to release another snapshot of emacs master 

### ISSUE THREAD

**Issue by kaushalmodi** [purcell/nix-emacs-ci#75]
Hello,

Can you please release another snapshot from emacs master? 

I am using the snapshot version as well for ox-hugo CI and it's failing with that version. Though, the bug is fixed on the latest emacs master. So once you update the snapshot, I can re-enable the CI for the snapshot version for ox-hugo.

Ref: https://github.com/kaushalmodi/ox-hugo/issues/630

Thanks!

**Comment by purcell** [comment]
FWIW, the snapshots get updated weekly now (since I did some work to enable that last week), and the snapshot will therefore get updated early next week. I don't really want to have to regenerate them more often in response to Emacs bugs, sorry, or to maintain some level of "stable snapshots" — occasional breakage is kinda the point of snapshots. All I can guarantee is that the snapshot versions compile and run.

**Comment by kaushalmodi** [comment]
Thanks for the reply.

> the snapshots get updated weekly now 

Thanks! That's exactly what I had requested in the other issue.  If it's already doing a weekly cron, that issue can be closed as well. I opened this ticket because in
https://github.com/purcell/nix-emacs-ci/commit/0765760fa0829a60c91dfcdcc2437691067ad85f, it says that the snapshot updates every month. 

 > I don't really want to have to regenerate them more often in response to Emacs bugs

Yes, I understand that. I made this request because I thought it was another month to the next snapshot. But weekly cron is perfect, and I wait for that. 

Thank you!

**Comment by purcell** [comment]
That's the `nixpkgs` snapshot, ie. the version of all of the system libs. There's a separate workflow for updating the Emacs snapshot version, and that runs weekly.

**Comment by kaushalmodi** [comment]
Certainly, I didn't understand how the emacs version gets updated. Thanks for clarifying. I'll then close that other issue too.

**Comment by purcell** [comment]
Awesome. I'm happy to have been prompted by a couple of people to make these updates more regular. It's still not *fully* automated — an update PR gets automatically created every week, but then I have to manually trigger CI and merge it. Better than nothing though!
