### ISSUE TITLE
How to print the commit hash of 'snapshot' emacs version in GHA?

### ISSUE THREAD

**Issue by kaushalmodi** [purcell/nix-emacs-ci#76]
Hello,

I am aware that if I look at the diff in the snapshot update commits, I can figure out the git commit used for that snapshot.

But can you enable printing of that hash from within that emacs binary?

I tried adding this: https://github.com/kaushalmodi/ox-hugo/blob/b94ab9b6f1525b7877d683caae58eed33dc7c843/test/setup-ox-hugo.el#L238

but I see that `--disable-build-details` is used and probably that's why `emacs-repository-version` is not printing the hash?

I see this output in GHA CI: https://github.com/kaushalmodi/ox-hugo/runs/6423749348?check_suite_focus=true#step:5:13

```
:: Version Check :: Emacs ::
GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu), built using commit 
    .. configure options: --prefix=/nix/store/ij8bkk6c4jxkfw8aq6mg9f922l1wkn73-emacs-snapshot --disable-build-details --with-modules --with-x=no --with-ns=no --with-xpm=no --with-jpeg=no --with-png=no --with-gif=no --with-tiff=no
    .. features: GMP GNUTLS JSON LIBXML2 MODULES NOTIFY INOTIFY PDUMPER SECCOMP SOUND THREADS ZLIB
```

**Comment by akirak** [comment]
FYI: emacs-overlay has a patch for setting the version (https://github.com/nix-community/emacs-overlay/commit/80df4c219966c8cd179e5f1b2089a5605f75cadb). The same patch would be applicable to nix-emacs-ci as well.

As a proof, `emacsPgtkGcc` from emacs-overlay (at a revision I am currently using) shows the following `describe-variable` output:

> emacs-repository-version is a variable defined in ‘version.el’.
> 
> Its value is "783dd6da31e3f0387e110972c0b9fe1f5acc4bba"

**Comment by kaushalmodi** [comment]
Thank you for implementing this!

**Comment by purcell** [comment]
The thanks goes mostly to @akirak for finding the snippet above.
