### ISSUE TITLE
Emacs 24.4 can't find let-alist

### ISSUE THREAD

**Issue by dajva** [purcell/nix-emacs-ci#8]
Thanks for starting up this project. Looks really promising. :)

I am trying to use this on travis but see some problems with emacs 24.4.
For some reason it fails to find the `let-alist` package. I am using *Cask* for dependency tracking. The `let-alist` depends on emacs 24.1 so should work fine.
This works fine when using *EVM*, both locally and on travis. I have not tried with nix locally since I really don't know how to set it up properly.

I know this is probably something you can't really help with but thought I report it here anyway in case there is some obvious source you could think of. Do you know if there is something in the setup that could cause such problems?

Here is the failing job: https://travis-ci.org/dajva/rg.el/jobs/587784855
Extracted error:
```
$ cask
682Making version-control local to wgrep-autoloads.el while let-bound!
683Wrote /home/travis/build/dajva/rg.el/.cask/24.5/elpa/wgrep-20181229.40/wgrep-autoloads.el
684Wrote /home/travis/build/dajva/rg.el/.cask/24.5/elpa/s-20180406.808/s-autoloads.el
685Wrote /home/travis/build/dajva/rg.el/.cask/24.5/elpa/shut-up-20180628.1830/shut-up-autoloads.el
686Wrote /home/travis/build/dajva/rg.el/.cask/24.5/elpa/dash-20190920.1035/dash-autoloads.el
687Wrote /home/travis/build/dajva/rg.el/.cask/24.5/elpa/undercover-20180403.1452/undercover-autoloads.el
688Wrote /home/travis/build/dajva/rg.el/.cask/24.5/elpa/ivy-20190825.1023/ivy-autoloads.el
689Wrote /home/travis/build/dajva/rg.el/.cask/24.5/elpa/find-file-in-project-20190914.524/find-file-in-project-autoloads.el
690Wrote /home/travis/build/dajva/rg.el/.cask/24.5/elpa/package-lint-20190908.2158/package-lint-autoloads.el
691Dependency flycheck failed to install: Package `let-alist-1.0.4' is unavailable
```

**Comment by purcell** [comment]
Interesting, yes, the Emacs appears unable to download the GNU package list: https://travis-ci.org/dajva/rg.el/jobs/587784855#L677. That Emacs version uses http by default for the ELPA archive URL, which usually works fine, whereas Cask uses https. And as detailed in #2, and changes to the ELPA site hosting, old Emacs versions built with non-ancient  GNUTLS can't access the current ELPA site over https. There's no easy way to override Cask's package URLs, so I think I'll have to backport the Emacs 26.3 fix to those old Emacsen.

**Comment by purcell** [comment]
Okay, this is now fixed: I made the decision to backport that patch. You should be able to restart your failed jobs to see if they now pass.

**Comment by dajva** [comment]
Works fine now. Thanks a lot.

**Comment by purcell** [comment]
Super, thanks for confirming.
