### ISSUE TITLE
Include the new elpa keys in older emacsen

### ISSUE THREAD

**Issue by dajva** [purcell/nix-emacs-ci#9]
I just got hit by the issue with the expired elpa keys discussed on emacs-devel here: https://lists.gnu.org/archive/html/emacs-devel/2019-02/msg00338.html

I had to add this to my travis scripts to get it working: https://github.com/dajva/rg.el/blob/master/tools/import-elpa-gpg-key.sh

Wonder if it makes sense to patch older versions here with the new `etc/package-keyring.gpg`?

I guess that would be another deviation from "what people actually has installed" though but maybe wouldn't have that much impact on the rest of the emacs behavior.

**Comment by purcell** [comment]
Interesting! I feel like it *would* make sense to patch the older versions. In general here I have to choose between making old Emacsen that:

1. can easily start up and be used for testing (generally with packages), and
2. will faithfully reproduce all the misbehaviour you'd experience trying to use such an old version in a modern environment.

I find I'm generally choosing option 1, but it's debatable which is "correct" in the context of CI. For example, for my `.emacs.d`, I'd actually want to know that old Emacsen might need to have `package-check-signatures` disabled, or the keyring updated.

**Comment by purcell** [comment]
This is now done, on a branch for now: https://github.com/purcell/nix-emacs-ci/compare/latest-package-keyring

**Comment by dajva** [comment]
Great. One issue with cask is that it's running on the same emacs that is being tested. So, it get's kind of hard to have bugs that affect cask in fundamental ways.
I guess this could also go into cask since cask is the package that is actually needing the updated keyring. 
Pretty surprising that the emacs maintainers issued a key without having a expiration renewal plan.

**Comment by purcell** [comment]
Merged now.
